export const sushi = [
  {
    id: 1,
    name: "Smoked Fish",
    img: require('./images/20190919_115312_рол з копченим лососем.jpg'),
    price: 112,
    currency: '₴',
    text: 'Rice, Nori, Cucumber, Sesame white, Mayonnaise, Smoked salmon',
    weight: '120g',
    active: false,
    count: 1,
  },
  {
    id: 2,
    name: "Philadelphia Green",
    img: require('./images/20190919_115708_філ. з авокадо.jpg'),
    price: 127,
    currency: '₴',
    text: 'Rice, Nori, Cream cheese, Cucumber, Sesame white, Avocado, Oil fish',
    weight: '115g',
    active: false,
    count: 1,
  },
  {
    id: 3,
    name: "Set",
    img: require('./images/20200312_161001_1111.jpg'),
    price: 238,
    currency: '₴',
    text: 'Rice, Nori, Cream cheese, Cucumber, Sesame white, Avocado, Oil fish',
    weight: '380g',
    active: false,
    count: 1,
  },
  {
    id: 4,
    name: "Oil Fish",
    img: require('./images/20190919_115733_філад. з масялною рибою.jpg'),
    price: 108,
    currency: '₴',
    text: 'Rice, Nori, Cream cheese, Cucumber, Sesame white, Avocado, Oil fish',
    weight: '120g',
    active: false,
    count: 1,
  },
  {
    id: 5,
    name: "Masago",
    img: require('./images/20190919_115057_масаго з лосоем.jpg'),
    price: 139.00,
    currency: '₴',
    text: 'Rice, Nori, Cream Cheese, Cucumber, Masago Caviar, Fresh Salmon',
    weight: '130g',
    count: 1,
  },
  {
    id: 6,
    name: "Hong Kong",
    img: require('./images/20190919_114832_гонконг.jpg'),
    price: 134,
    currency: '₴',
    text: 'Rice, Nori, Cream cheese, Unagi sauce, Cucumber, Sesame white, Chives, Eel, Fresh salmon',
    weight: '160g',
    active: false,
    count: 1,
  },
]



export const sushiUkr = [
  {
    id: 1,
    name: "Smog Fish",
    img: require('./images/20190919_115312_рол з копченим лососем.jpg'),
    price: 112,
    currency: '₴',
    text: 'Рис, Норі, Огірок, Кунжут білий, Майонез, Лосось копчений',
    weight: '120г',
    active: false,
    count: 1,
  },
  {
    id: 2,
    name: "Philadelphia Green",
    img: require('./images/20190919_115708_філ. з авокадо.jpg'),
    price: 127,
    currency: '₴',
    text: 'Рис, Норі, Крем-сир, Огірок, Кунжут білий, Авокадо, Масляна риба',
    weight: '115г',
    active: false,
    count: 1,
  },
  {
    id: 3,
    name: "Set",
    img: require('./images/20200312_161001_1111.jpg'),
    price: 238,
    currency: '₴',
    text: 'Рис, Норі, Крем-сир, Огірок, Кунжут білий, Авокадо, Масляна риба',
    weight: '380г',
    active: false,
    count: 1,
  },
  {
    id: 4,
    name: "Butter Fish",
    img: require('./images/20190919_115733_філад. з масялною рибою.jpg'),
    price: 108,
    currency: '₴',
    text: 'Рис, Норі, Крем-сир, Огірок, Кунжут білий, Авокадо, Масляна риба',
    weight: '120г',
    active: false,
    count: 1,
  },
  {
    id: 5,
    name: "Masago",
    img: require('./images/20190919_115057_масаго з лосоем.jpg'),
    price: 139.00,
    currency: '₴',
    text: 'Рис, Норі, Крем-сир, Огірок, Ікра масаго, Лосось свіжий',
    weight: '130г',
    count: 1,
  },
  {
    id: 6,
    name: "Hong Kong",
    img: require('./images/20190919_114832_гонконг.jpg'),
    price: 134,
    currency: '₴',
    text: 'Рис, Норі, Крем-сир, соус Унагі, Огірок, Кунжут білий, Зелена цибуля, Вугор, Лосось свіжий',
    weight: '160г',
    active: false,
    count: 1,
  },
]
